version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: adbentur_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: adbenturBD
      MYSQL_USER: adbenturuser
      MYSQL_PASSWORD: adbenturpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local
